### ISSUE TITLE
Generated model classes do not copy fields from parent classes

### ISSUE THREAD

**Issue by vladaman** [angel-dart/serialize#35]
When I use @serializable(autoIdAndDateFields=false) it no longer generates Model classes such as createdAt but ignores my parent class fields

```
class _User extends MyModel {
...
}
class MyModel {
   String willNotBePresent; // this is not generated.
}

```

**Comment by thosakwe** [comment]
Feel free to send a PR, as this is not a common use case.

Think of generated model classes as constant entities, not as plain old data objects. If you need polymorphism, just make sure `User implements MyModel`, and that it has *its own field*, ex. ‘@override String get willNotBePresent`. This pattern is well-supported, and I’ve used it before.

**Comment by thosakwe** [comment]
There are potential traps that come from automatically extending *all* fields of the parent class, because then the generator would very quickly start serializing every property from `Object`, `dynamic`, etc., like hashCode, and other fields that would easily just become noise in JSON.

The current pattern is basically a “whitelist” of fields, so ideally just treat the Model class as a specification of what your JSON should look like.

**Comment by thosakwe** [comment]
Closing this now, as it's neither a problem, nor a common use case. Plus, there is already functionality available to accomplish what you desire.
